language: php
matrix:
  fast_finish: true
  include:
  - php: nightly
    env:
        - PHPUNIT=true
        - DB_CONNECTION=mysql
  - php: 7.2
    env:
        - PHPUNIT=true
        - DB_CONNECTION=mysql
  - php: 7.1
    env:
        - PHPUNIT=true
        - DB_CONNECTION=mysql
  - php: 7.0
    env:
        - PHPUNIT=true
        - DB_CONNECTION=mysql
  - php: 5.6
    env: PHPUNIT=false
before_install:
  - if [ $PHPUNIT = false ]; then php ./tests/travis/remove-require-dev.php; fi
install:
  - composer install
script:
  - ./tests/lint.bash
  - if [ $PHPUNIT = true ]; then ./vendor/bin/phpunit --debug --coverage-clover=coverage.xml; fi
after_success:
  - if [ $PHPUNIT = true ]; then bash <(curl -s https://codecov.io/bash); fi
